spring:
  application:
    name: emqx-http-sdk-sample
emqx:
  http:
    sdk:
      url: "http://localhost:8081"
      app-id: "admin"
      app-secret: "public"
      # 禁用部分Api
      disabled:
        - client